name: Build BLDC

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["V0_6", "V0_5"]
        limits: [null, "_no_limits"]  

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install ARM SDK
        run: make arm_sdk_install

      - name: Build Firmware
        run: |
          make MP2_${{ matrix.version }}${{ matrix.limits }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: MP2_${{ matrix.version }}${{ matrix.limits }}_FW
          path: build/MP2_${{ matrix.version }}${{ matrix.limits }}/MP2_${{ matrix.version }}${{ matrix.limits }}.bin 
